package edu.yu.marketmaker.model;

/**
 * Authoritative net quantity held for a symbol.
 * Object to hold position generated by the Trading State Service.
 * A position is updated by applying recorded fills.
 * @param symbol ticker
 * @param netQuantity positive for long, negative for short
 * @param version monotonic per symbol
 * @param lastFillId
 */
public record Position(String symbol, int netQuantity, long version, long lastFillId) {
}
